// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WindowsyProjekt.Repository;

namespace WindowsyProjekt.Migrations
{
    [DbContext(typeof(WinProjDbContext))]
    partial class WinProjDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WindowsyProjekt.Repository.Models.Street", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Additional");

                    b.Property<string>("City");

                    b.Property<string>("PostCode");

                    b.Property<string>("StreetCordX");

                    b.Property<string>("StreetCordY");

                    b.Property<string>("StreetName");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Streets");
                });

            modelBuilder.Entity("WindowsyProjekt.Repository.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Country")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreateAccountDate");

                    b.Property<DateTime?>("DeleteAccountDate");

                    b.Property<string>("Email");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasDefaultValue("");

                    b.Property<int>("IsVerified");

                    b.Property<string>("Password");

                    b.Property<string>("PersonName")
                        .HasMaxLength(100);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(12);

                    b.Property<int>("UserType");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(6);

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
